name: Typecho Build Release Ci
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Build
      run: |
        mkdir build
        cp -r LICENSE.txt index.php install.php admin install usr var build/
        mkdir build/usr/uploads/
        chmod 755 build/usr/uploads/
        rm -rf build/admin/src
        rm -rf build/usr/themes/classic-22/static/scss
        cd build && zip -q -r typecho.zip * && mv typecho.zip ../ && cd -
    - name: Upload Release Asset
      run: gh release upload "${{ github.event.release.tag_name }}" ./typecho.zip --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Trigger language build
      run: |
        curl -XPOST -H "Authorization: token ${{ secrets.WORKFLOW_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/wjm13206/typecho/actions/workflows/update.yml/dispatches --data '{"ref": "master"}'